//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mvc_Angular_Crud_VBNET.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Produtos
    {
        public int Id { get; set; }
        public string ProdutoNome { get; set; }
        public Nullable<decimal> ProdutoPreco { get; set; }
    }
}
